---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Использование сайта (включая все его функции, контент и оформление) должна строго соответствовать всем требованиям действующего законодательства Российской Федерации.
  - Сайт (в том числе его каталоги и карточки товаров) должен всегда содержать актуальную информацию о наличии (в том числе количестве) товаров.
  - На сайте должна быть предусмотрена форма обратной связи, с помощью которой пользователь может обратиться в техническую поддержку или администрацию магазина для решения любых вопросов.
  - Пользователь должен иметь возможность зарегистрироваться и создать свой уникальный "Личный кабинет" на сайте. После регистрации пользователь сможет авторизоваться в системе, используя свои логин и пароль.
  - Изображения (фотографии, иллюстрации) и описание товара (включая его характеристики) должны соответствовать действительности и не вводить пользователя в заблуждение.
